### PR TITLE
Add read sdm code

### PR DESCRIPTION
**Pull request by nausikaa8**

### CODE REVIEW

**Comment by ofgulban** [comment]
Thanks for the PR @nausikaa8 :),

Would it be possible for you to send me your SDM data (separately from this PR) so that I can, (1) check your script, (2) zip it and upload to the `test_data` folder in the future?

**Comment by ofgulban** [comment]
I have received your email now and see that the SDM file is already included. So please ignore my previous request.

**Comment by nausikaa8** [comment]
Thank you, @ofgulban :)

**Comment by ofgulban** [comment]
@nausikaa8 , see my changes to your `read_sdm` contribution in the following commits:
1. 600955f7dd9f6cc8a0c1cec737e3af619a61c2dc
2. f4296b1eadc0a8529d68c873b297d2ddc3db7bf0
3. 3b2798a2c4036131e9c0da43752e4857aca385e4
4. e33457d007a4bf7d2fac7c23f93113df9cb9f3e4
5. c38f2ec9ccb1df3b3f35faed0417ccbb42b4900c

Overall, 1-3 are easy issues, these can be addressed by using PEP8 and PEP257 linters in your text editor. 4 and 5 are mainly data structure decisions combined with changes to reduce the code length. I have explained my reasons to make these changes in the commit notes, you can have a look. Let me know what you think.

**Pull request merged**
